### PR TITLE
[NEW] Add table of contents

### PR DESCRIPTION
**Pull request by mstuttgart**
Added table of content to make easy jump to sections. :+1:

### CODE REVIEW

**Comment by pauleveritt** [comment]
Good idea, thanks. Should we start a CONTRIBUTORS.md for each person (like you) that does a push?

**Comment by mstuttgart** [comment]
Why close the PR? Something wrong with the code? :confused: 
 
I can add a CONTRIBUTORS.md file.

**Comment by pauleveritt** [comment]
My mistake, wrong button.

**Comment by mstuttgart** [comment]
No problem :blush: Thanks! :+1:

**Pull request merged**
