### PR TITLE
Add Flask Live Templates link

### PR DESCRIPTION
**Pull request by mstuttgart**
Hi! This PR add the follow items:

* [NEW] Create Live Templates section
* [NEW] Add link to PyCharm Flask Live Templates

Awesome idea. Thanks :)

### CODE REVIEW

**Comment by pauleveritt** [comment]
Holy crap, how did you find this? :)

We're considering keeping it quiet until it fills out a little, and until we learn a bit more about the kinds of information to collect and what to keep/reject. But your PR certainly is what we're looking for. Kudos to you for being the first, with something really good.

**Comment by mstuttgart** [comment]
I was thinking about creating a similar project, but I did a search and I ended up finding your project. Awesome project :+1: 

I intend to submit more content soon for the project. :)

**Comment by pauleveritt** [comment]
In that case, please take some notes about how we should to this. I can send you some notes I have, or put them in tickets.

—Paul

**Comment by pauleveritt** [comment]
Very good, thanks. We might choose to make this section "Plugins" if we can't find many more live templates.

**Comment by mstuttgart** [comment]
@pauleveritt thanks! I will add more templates in soon. :+1:

**Pull request merged**
